module.exports = Object.assign({}, {
  admin_response: {
    EMAIL_VALIDATION_ADMIN: "Please provide email address to login!",
    PASSWORD_VALIDATION_ADMIN: "Please provide password to login",
    VALID_EMAIL_ADMIN: "Please provide valid email address to login",
    NEW_ADDED: "Created successfully",
    UPDATED: "Updated successfully",
    UPDATED_STATUS: "Status updated successfully",
    NEW_ROLE: "New Role has been added successfully!",
    SAME_ROLE_EXIST: "Role with same name already exist!",
    UPDATED_ROLE: "Role has been updated successfully!",
    NEW_PERMISSION: "New Permission has been added successfully!",
    SAME_PERMISSION_EXIST: "Permission with same name already exist!",
    UPDATED_PERMISSON: "Permission has been updated successfully!",
    NEW_CATEGORY: "New Category has been added successfully!",
    SAME_CATEGORY_EXIST: "Category with same name already exist!",
    UPDATED_CATEGORY: "Category has been updated successfully!",
    BASIC_AUTH: "Please sign-in with correct credentials!",
    LOGGED_IN_MSG: "You are now logged in!!",
    LOGGED_OUT_MSG: "You are now logged out of the Dashboard!!",
    ACADEMIC_YEAR_UPDATED: "Academic Year Updated!",
    SOMETHING_ERR: "Something went wrong!",
    ACTIVE: "active",
    INACTIVE: "inactive",
    DESC: -1,
    ASC: 1,
    PASSWORD_NOT_MATCHING: "Password do not match!",
    OUTSIDE_USER: "Oops! Seems like you are not authorized!",
    FILE_TYPE_NOT_ALLOWED: "This file type is not allowed!",
    NEW_CENTER: "New Center has been added successfully!",
    SAME_CENTER_EXIST: "Center with same name already exist!",
    UPDATED_CENTER: "Center has been updated successfully!",
    NEW_USER: "New User Created Successfully!!",
    SAME_USER_EXIST: "User already exist with same email address!!",
    UPDATED_USER: "User has been updated successfully!",
    NEW_COUNTRY: "New country created successfully",
    COMMON_UPDATED: "Updated Successfully!",
    SAME_CATEGORY_EXIST: "Course already exist with same name!",
    NEW_COURSE: "New course has been added!",
    EMPLOYEE_NOT_FOUND: "Employee not found!",
    NEW_ZONE: "Zone created successfully!",
    UPDATED_ZONE: "Zone updated successfully!",
    NEW_PROGRAM: "New Program created successfully!",
    NEW_PROGRAM_CATEGORY: "New program category has been added successfully!",
    FILE_DELETED: "File Deleted!",
    NEW_MESSAGE:"New message has been added!",
    SAME_EXIST: "User found in system. Please try again."
  },
  redirect_url: {
    ALL_PERMISSION_URL: "/admin/uac/permission/all/",
    ALL_ROLE_URL: "/admin/uac/role/all/",
    DASHBOARD_URL: "/admin/dashboard/",
    ALL_USER: "/admin/employee/all",
    LOGIN_PAGE: "/admin/account/login",
    ALL_ACADEMIC_YEAR: "/admin/academic/year/all",
    ALL_CENTER: "/admin/center/all",
    ALL_COUNTRY: "/admin/country/all",
    ALL_COURSE: "/admin/course/all",
    ALL_ZONE: "/admin/zone/all",
    ALL_PROGRAM: "/admin/program/all",
    ALL_PROGRAM_CATEGORY: "/admin/programcategory/all",
    ALL_MESSAGE: "/admin/message/all"
  },
  permission_name: {
    USER_ADD_USER: "UserAddUser",
    USER_EDIT_USER: "UserEditUser",
    USER_VIEW_MASTER: "UserViewMaster",
    USER_VIEW_LISTING: "UserViewListing",
    USER_VIEW_PASSWORD: "UserViewPassword",
    USER_SEND_MAIL: "UserSendMail",
    USER_RESET_PASSWORD: "UserResetPassword",
    ACADEMIC_YEAR_MASTER: "AcademicYearViewMaster",
    ACADEMIC_YEAR_LISTING: "AcademicYearViewListing",
    ACADEMIC_YEAR_ADD: "AcademicYearAdd",
    ACADEMIC_YEAR_EDIT: "AcademicYearEdit",
    MSG_VIEW_MASTER: "MessageViewMaster",
    MSG_LISTING: "MessageViewListing",
    MSG_EDIT: "MessageEdit",
    MSG_ADD: "MessageAdd",
    LEAD_ADD: "LeadAdd",
    LEAD_EDIT: "LeadEdit",
    LEAD_LISTING: "LeadListing",
    LEAD_TRANSFER: "LeadTransfer",
    LEAD_IMPORT: "LeadImport",
    LEAD_EXPORT: "LeadExport",
    FOLLOWUP_ADD: "FollowUpAdd",
    FOLLOWUP_EDIT: "FollowUpEdit",
    FOLLOWUP_LISTING: "FollowUpListing",
    CONTENT_VIEW_LISTING: "ContentViewListing",
    REPORT_MTD: "ReportsMTD",
    REPORT_YTD: "ReportsYTD"
  }
})